services:
  storage-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple-object-storage
    ports:
      - "50001:50001"
    environment:
      - PORT=50001
    volumes:
      # Mount uploads directory untuk persistent storage
      - ./uploads:/root/uploads
    restart: unless-stopped
    networks:
      - main_net

networks:
  main_net:
    external: true

volumes:
  uploads:
